version: '2'
services:
    rabbitmq:
        image: rabbitmq:3.6-management
        restart: always
        ports:
            - "15672:15672"
            - "5672:5672"
        environment:
            - RABBITMQ_DEFAULT_USER=airflow
            - RABBITMQ_DEFAULT_PASS=airflow
            - RABBITMQ_DEFAULT_VHOST=airflow

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: mrmaksimize/airflow:latest
        restart: always
        volumes:
            - ${PATH_PREFIX}/poseidon:/usr/local/airflow/poseidon
            - ${PATH_PREFIX}/poseidon/data:/data
            #- ${PATH_PREFIX}/poseidon/logs:/usr/local/airflow/logs
        depends_on:
            - postgres
            - rabbitmq
        environment:
            - LOAD_EX=n
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - EXECUTOR=Celery
            - AIRFLOW_HOME=/usr/local/airflow
        env_file:
            - ${PATH_PREFIX}/poseidon/${ENV_FILE}
        ports:
            - "8080:8080"
        links:
            - postgres:postgres
            - fmeengine:fmeengine
        entrypoint: /usr/local/airflow/poseidon/custom_entrypoint.sh
        command: webserver

    flower:
        image: mrmaksimize/airflow:latest
        restart: always
        depends_on:
            - rabbitmq
        environment:
            - EXECUTOR=Celery
            - AIRFLOW_HOME=/usr/local/airflow
        ports:
            - "5555:5555"
        links:
            - rabbitmq:rabbitmq
        command: flower

    scheduler:
        image: mrmaksimize/airflow:latest
        restart: always
        depends_on:
            - webserver
        volumes:
            - ${PATH_PREFIX}/poseidon:/usr/local/airflow/poseidon
            - ${PATH_PREFIX}/poseidon/data:/data
            #- ${PATH_PREFIX}/poseidon/logs:/usr/local/airflow/logs
        environment:
            - LOAD_EX=n
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - EXECUTOR=Celery
            - AIRFLOW_HOME=/usr/local/airflow
        env_file:
            - ${PATH_PREFIX}/poseidon/${ENV_FILE}
        links:
            - fmeengine:fmeengine
        command: scheduler -n 1

    worker:
        image: mrmaksimize/airflow:latest
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ${PATH_PREFIX}/poseidon:/usr/local/airflow/poseidon
            - ${PATH_PREFIX}/poseidon/data:/data
            #- ${PATH_PREFIX}/poseidon/logs:/usr/local/airflow/logs
        environment:
            - LOAD_EX=n
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - EXECUTOR=Celery
            - AIRFLOW_HOME=/usr/local/airflow
        env_file:
            - ${PATH_PREFIX}/poseidon/${ENV_FILE}
        links:
            - fmeengine:fmeengine
        entrypoint: /usr/local/airflow/poseidon/custom_entrypoint.sh
        command: worker

    fmeengine:
        image: safesoftware/fme-engine-2017:latest
        restart: always
        volumes:
            - ${PATH_PREFIX}/poseidon:/poseidon
            - ${PATH_PREFIX}/poseidon/data:/data
            - ${PATH_PREFIX}/poseidon/logs:/fmeengine/logs
        ports:
            - "7777:7777"
