postgres:
    image: postgres
    environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow

rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
        - "15672:15672"
        - "5672:5672"
    environment:
        - RABBITMQ_DEFAULT_USER=airflow
        - RABBITMQ_DEFAULT_PASS=airflow
        - RABBITMQ_DEFAULT_VHOST=airflow

webserver:
    image: mrmaksimize/airflow:latest
    restart: always
    volumes:
         - /Users/MrMaksimize/Code/airflow_dags:/usr/local/airflow/dags
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    ports:
        - "8080:8080"
    links:
        - postgres:postgres
        - rabbitmq:rabbitmq
        - worker:worker
        - scheduler:scheduler
        - fmeengine:fmeengine
    command: webserver

flower:
    image: mrmaksimize/airflow:latest
    restart: always
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    ports:
        - "5555:5555"
    links:
        - rabbitmq:rabbitmq
    command: flower

scheduler:
    image: mrmaksimize/airflow:latest
    restart: always
    volumes:
        - /Users/MrMaksimize/Code/airflow_dags:/usr/local/airflow/dags
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    links:
        - postgres:postgres
        - rabbitmq:rabbitmq
        - fmeengine:fmeengine
    command: scheduler -n 5

worker:
    image: mrmaksimize/airflow:latest
    restart: always
    volumes:
          - /Users/MrMaksimize/Code/airflow_dags:/usr/local/airflow/dags
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    links:
        - postgres:postgres
        - rabbitmq:rabbitmq
        - fmeengine:fmeengine
    command: worker

fmeengine:
    image: safesoftware/fme-engine-2017:latest
    restart: always
    volumes:
        - /Users/MrMaksimize/Code/ETL:/fmeengine/workspaces
        - /Users/MrMaksimize/Code/logs:/fmeengine/logs
    ports:
        - "7777:7777"
