version: '2'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${AIRFLOW_DB_USER}
            - POSTGRES_PASSWORD=${AIRFLOW_DB_PASS}
            - POSTGRES_DB=airflow
    webserver:
        image: mrmaksimize/airflow:latest
        restart: always
        volumes:
            - ${PATH_PREFIX}/poseidon:/usr/local/airflow/poseidon
            - ${PATH_PREFIX}/poseidon/data:/data
            #- ${PATH_PREFIX}/poseidon/logs:/usr/local/airflow/logs
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - AIRFLOW_HOME=/usr/local/airflow
            - EXECUTOR=Sequential
            - AIRFLOW_DB_USER=${AIRFLOW_DB_USER}
            - AIRFLOW_DB_PASS=${AIRFLOW_DB_PASS}
            - AIRFLOW_RMQ_USER=${AIRFLOW_RMQ_USER}
            - AIRFLOW_RMQ_PASS=${AIRFLOW_RMQ_PASS}
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/airflow.db
            - AIRFLOW__CELERY__BROKER_URL=amqp://${AIRFLOW_RMQ_USER}:${AIRFLOW_RMQ_PASS}@rabbitmq:5672/airflow
            - AIRFLOW__CELERY__CELERY_RESULT_BACKEND=amqp://${AIRFLOW_RMQ_USER}:${AIRFLOW_RMQ_PASS}@rabbitmq:5672/airflow
            - AIRFLOW_CONN_AIRFLOW_DB=sqlite:////usr/local/airflow/airflow.db
        env_file:
            - ${PATH_PREFIX}/poseidon/${ENV_FILE}
        ports:
            - "8080:8080"
            - "8888:8888"
            - "9999:9999"
        links:
            - fmeengine:fmeengine
        entrypoint: /usr/local/airflow/poseidon/custom_entrypoint.sh
        command: webserver
    fmeengine:
        image: safesoftware/fme-engine-2017:latest
        restart: always
        volumes:
            - ${PATH_PREFIX}/poseidon:/poseidon
            - ${PATH_PREFIX}/poseidon/data:/data
            - ${PATH_PREFIX}/poseidon/logs:/fmeengine/logs
        ports:
            - "7777:7777"
