version: '2'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${AIRFLOW_DB_USER}
            - POSTGRES_PASSWORD=${AIRFLOW_DB_PASS}
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"
        volumes:
            - ${PATH_PREFIX}/poseidon/db/data:/var/lib/postgresql/data

    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${AIRFLOW_DB_PASS}
            - MYSQL_DATABASE=vpm_temp

    webserver:
        image: mrmaksimize/airflow:latest
        restart: always
        volumes:
            - ${PATH_PREFIX}/poseidon:/usr/local/airflow/poseidon
            - ${PATH_PREFIX}/poseidon/data:/data
            #- ${PATH_PREFIX}/poseidon/logs:/usr/local/airflow/logs
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - AIRFLOW_HOME=/usr/local/airflow
            - AIRFLOW_DB_USER=${AIRFLOW_DB_USER}
            - AIRFLOW_DB_PASS=${AIRFLOW_DB_PASS}
            - AIRFLOW_RMQ_USER=${AIRFLOW_RMQ_USER}
            - AIRFLOW_RMQ_PASS=${AIRFLOW_RMQ_PASS}
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@postgres/airflow
            - AIRFLOW__CELERY__BROKER_URL=amqp://${AIRFLOW_RMQ_USER}:${AIRFLOW_RMQ_PASS}@rabbitmq:5672/airflow
            - AIRFLOW__CELERY__CELERY_RESULT_BACKEND=amqp://${AIRFLOW_RMQ_USER}:${AIRFLOW_RMQ_PASS}@rabbitmq:5672/airflow
            - AIRFLOW_CONN_AIRFLOW_DB=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@postgres/airflow
            - AIRFLOW_CONN_VPM_TEMP=mysql+mysqldb://root:${AIRFLOW_DB_PASS}@mysql:3306/vpm_temp
        env_file:
            - ${PATH_PREFIX}/poseidon/${ENV_FILE}
        ports:
            - "8080:8080"
        links:
            - mysql:mysql
            - postgres:postgres
            - fmeengine:fmeengine
        entrypoint: /usr/local/airflow/poseidon/custom_entrypoint.sh
        command: webserver

    scheduler:
        image: mrmaksimize/airflow:latest
        restart: always
        volumes:
            - ${PATH_PREFIX}/poseidon:/usr/local/airflow/poseidon
            - ${PATH_PREFIX}/poseidon/data:/data
            #- ${PATH_PREFIX}/poseidon/logs:/usr/local/airflow/logs
        depends_on:
            - webserver
        environment:
            - LOAD_EX=n
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - EXECUTOR=Local
            - AIRFLOW_HOME=/usr/local/airflow
            - AIRFLOW_DB_USER=${AIRFLOW_DB_USER}
            - AIRFLOW_DB_PASS=${AIRFLOW_DB_PASS}
            - AIRFLOW_RMQ_USER=${AIRFLOW_RMQ_USER}
            - AIRFLOW_RMQ_PASS=${AIRFLOW_RMQ_PASS}
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@postgres/airflow
            - AIRFLOW__CELERY__BROKER_URL=amqp://${AIRFLOW_RMQ_USER}:${AIRFLOW_RMQ_PASS}@rabbitmq:5672/airflow
            - AIRFLOW__CELERY__CELERY_RESULT_BACKEND=amqp://${AIRFLOW_RMQ_USER}:${AIRFLOW_RMQ_PASS}@rabbitmq:5672/airflow
            - AIRFLOW_CONN_AIRFLOW_DB=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@postgres/airflow
            - AIRFLOW_CONN_VPM_TEMP=mysql+mysqldb://root:${AIRFLOW_DB_PASS}@mysql:3306/vpm_temp
        env_file:
            - ${PATH_PREFIX}/poseidon/${ENV_FILE}
        links:
            - mysql:mysql
            - fmeengine:fmeengine
        entrypoint: /usr/local/airflow/poseidon/custom_entrypoint.sh
        command: scheduler -n 1

    fmeengine:
        image: safesoftware/fme-engine-2017:latest
        restart: always
        volumes:
            - ${PATH_PREFIX}/poseidon:/poseidon
            - ${PATH_PREFIX}/poseidon/data:/data
            - ${PATH_PREFIX}/poseidon/logs:/fmeengine/logs
        ports:
            - "7777:7777"
