version: '2'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: mrmaksimize/airflow:latest
        restart: always
        volumes:
            - ~/Code/sd_airflow/poseidon:/usr/local/airflow/poseidon
            - ~/Code/sd_airflow/poseidon/data:/data
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - AIRFLOW_HOME=/usr/local/airflow
            - EXECUTOR=Sequential
        env_file: 
            - ~/Code/sd_airflow/docker-airflow/config/local.env
        ports:
            - "8080:8080"
        links:
            - fmeengine:fmeengine
        entrypoint: /usr/local/airflow/poseidon/custom_entrypoint.sh
        command: webserver
    

    fmeengine:
        image: safesoftware/fme-engine-2017:latest
        restart: always
        volumes:
            - ~/Code/sd_airflow/poseidon:/poseidon
            - ~/Code/sd_airflow/poseidon/data:/data
            - ~/Code/sd_airflow/poseidon/logs:/fmeengine/logs
        ports:
            - "7777:7777"
