version: '2.1'
services:
    webserver:
        image: andrell81/docker-airflow:latest
        restart: always
        volumes:
            - ./poseidon:/usr/local/airflow/poseidon
            - ./data:/data
        environment:
            - AIRFLOW_HOME=/usr/local/airflow
            - LOAD_EX=n
            - EXECUTOR=Sequential
              # From environment specific .env
            - SD_ENV=${SD_ENV}
            - SECRETLY_NAMESPACE=${SD_ENV}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_REGION=${AWS_REGION}
            - AIRFLOW_CONN_S3DATA="S3://${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}@S3"
            - AIRFLOW_CONN_S3LOG="S3://${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}@poseidon-logs-${SD_ENV}"
            - PYTHONPATH="/usr/local/airflow/poseidon"
        ports:
            - "1187:1187"
            - "8888:8888"
            - "8000:8000"
            - "8999:8999"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
