version: '2'
services:
    rabbitmq:
        image: rabbitmq:3.6-management
        restart: always
        ports:
            - "15672:15672"
            - "5672:5672"
        environment:
            - RABBITMQ_DEFAULT_USER=${AIRFLOW_RMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${AIRFLOW_RMQ_PASS}
            - RABBITMQ_DEFAULT_VHOST=airflow

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${AIRFLOW_DB_USER}
            - POSTGRES_PASSWORD=${AIRFLOW_DB_PASS}
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"
        volumes:
            - ${PATH_PREFIX}/poseidon/db/data:/var/lib/postgresql/data

    webserver:
        image: mrmaksimize/airflow:latest
        restart: always
        volumes:
            - ${PATH_PREFIX}/poseidon:/usr/local/airflow/poseidon
            - ${PATH_PREFIX}/poseidon/data:/data
            #- ${PATH_PREFIX}/poseidon/logs:/usr/local/airflow/logs
        depends_on:
            - postgres
            - rabbitmq
        environment:
            - LOAD_EX=n
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - EXECUTOR=Celery
            - AIRFLOW_HOME=/usr/local/airflow
            - AIRFLOW_DB_USER=${AIRFLOW_DB_USER}
            - AIRFLOW_DB_PASS=${AIRFLOW_DB_PASS}
            - AIRFLOW_RMQ_USER=${AIRFLOW_RMQ_USER}
            - AIRFLOW_RMQ_PASS=${AIRFLOW_RMQ_PASS}
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@postgres/airflow
            - AIRFLOW__CELERY__BROKER_URL=amqp://${AIRFLOW_RMQ_USER}:${AIRFLOW_RMQ_PASS}@rabbitmq:5672/airflow
            - AIRFLOW__CELERY__CELERY_RESULT_BACKEND=amqp://${AIRFLOW_RMQ_USER}:${AIRFLOW_RMQ_PASS}@rabbitmq:5672/airflow
            - AIRFLOW_CONN_AIRFLOW_DB=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@postgres/airflow
        env_file:
            - ${PATH_PREFIX}/poseidon/${ENV_FILE}
        ports:
            - "8080:8080"
        links:
            - postgres:postgres
            - fmeengine:fmeengine
        entrypoint: /usr/local/airflow/poseidon/custom_entrypoint.sh
        command: webserver

    flower:
        image: mrmaksimize/airflow:latest
        restart: always
        depends_on:
            - rabbitmq
        volumes:
            - ${PATH_PREFIX}/poseidon:/usr/local/airflow/poseidon
            - ${PATH_PREFIX}/poseidon/data:/data
            #- ${PATH_PREFIX}/poseidon/logs:/usr/local/airflow/logs
        environment:
            - EXECUTOR=Celery
            - AIRFLOW_HOME=/usr/local/airflow
            - AIRFLOW_DB_USER=${AIRFLOW_DB_USER}
            - AIRFLOW_DB_PASS=${AIRFLOW_DB_PASS}
            - AIRFLOW_RMQ_USER=${AIRFLOW_RMQ_USER}
            - AIRFLOW_RMQ_PASS=${AIRFLOW_RMQ_PASS}
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@postgres/airflow
            - AIRFLOW__CELERY__BROKER_URL=amqp://${AIRFLOW_RMQ_USER}:${AIRFLOW_RMQ_PASS}@rabbitmq:5672/airflow
            - AIRFLOW__CELERY__CELERY_RESULT_BACKEND=amqp://${AIRFLOW_RMQ_USER}:${AIRFLOW_RMQ_PASS}@rabbitmq:5672/airflow
            - AIRFLOW_CONN_AIRFLOW_DB=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@postgres/airflow
        env_file:
            - ${PATH_PREFIX}/poseidon/${ENV_FILE}
        ports:
            - "5555:5555"
        links:
            - rabbitmq:rabbitmq
        entrypoint: /usr/local/airflow/poseidon/custom_entrypoint.sh
        command: flower

    scheduler:
        image: mrmaksimize/airflow:latest
        restart: always
        depends_on:
            - webserver
        volumes:
            - ${PATH_PREFIX}/poseidon:/usr/local/airflow/poseidon
            - ${PATH_PREFIX}/poseidon/data:/data
            #- ${PATH_PREFIX}/poseidon/logs:/usr/local/airflow/logs
        environment:
            - LOAD_EX=n
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - EXECUTOR=Celery
            - AIRFLOW_HOME=/usr/local/airflow
            - AIRFLOW_DB_USER=${AIRFLOW_DB_USER}
            - AIRFLOW_DB_PASS=${AIRFLOW_DB_PASS}
            - AIRFLOW_RMQ_USER=${AIRFLOW_RMQ_USER}
            - AIRFLOW_RMQ_PASS=${AIRFLOW_RMQ_PASS}
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@postgres/airflow
            - AIRFLOW__CELERY__BROKER_URL=amqp://${AIRFLOW_RMQ_USER}:${AIRFLOW_RMQ_PASS}@rabbitmq:5672/airflow
            - AIRFLOW__CELERY__CELERY_RESULT_BACKEND=amqp://${AIRFLOW_RMQ_USER}:${AIRFLOW_RMQ_PASS}@rabbitmq:5672/airflow
            - AIRFLOW_CONN_AIRFLOW_DB=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@postgres/airflow
        env_file:
            - ${PATH_PREFIX}/poseidon/${ENV_FILE}
        links:
            - fmeengine:fmeengine
        entrypoint: /usr/local/airflow/poseidon/custom_entrypoint.sh
        command: scheduler -n 1

    worker:
        image: mrmaksimize/airflow:latest
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ${PATH_PREFIX}/poseidon:/usr/local/airflow/poseidon
            - ${PATH_PREFIX}/poseidon/data:/data
            #- ${PATH_PREFIX}/poseidon/logs:/usr/local/airflow/logs
        environment:
            - LOAD_EX=n
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - EXECUTOR=Celery
            - AIRFLOW_HOME=/usr/local/airflow
            - AIRFLOW_DB_USER=${AIRFLOW_DB_USER}
            - AIRFLOW_DB_PASS=${AIRFLOW_DB_PASS}
            - AIRFLOW_RMQ_USER=${AIRFLOW_RMQ_USER}
            - AIRFLOW_RMQ_PASS=${AIRFLOW_RMQ_PASS}
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@postgres/airflow
            - AIRFLOW__CELERY__BROKER_URL=amqp://${AIRFLOW_RMQ_USER}:${AIRFLOW_RMQ_PASS}@rabbitmq:5672/airflow
            - AIRFLOW__CELERY__CELERY_RESULT_BACKEND=amqp://${AIRFLOW_RMQ_USER}:${AIRFLOW_RMQ_PASS}@rabbitmq:5672/airflow
            - AIRFLOW_CONN_AIRFLOW_DB=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@postgres/airflow
        env_file:
            - ${PATH_PREFIX}/poseidon/${ENV_FILE}
        links:
            - fmeengine:fmeengine
        entrypoint: /usr/local/airflow/poseidon/custom_entrypoint.sh
        command: worker

    fmeengine:
        image: safesoftware/fme-engine-2017:latest
        restart: always
        volumes:
            - ${PATH_PREFIX}/poseidon:/poseidon
            - ${PATH_PREFIX}/poseidon/data:/data
            - ${PATH_PREFIX}/poseidon/logs:/fmeengine/logs
        ports:
            - "7777:7777"
