version: '2'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    webserver:
        image: mrmaksimize/airflow:latest
        restart: always
        volumes:
            - ${PATH_PREFIX}/poseidon:/usr/local/airflow/poseidon
            - ${PATH_PREFIX}/poseidon/data:/data
            - ${PATH_PREFIX}/poseidon/logs:/usr/local/airflow/logs
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - AIRFLOW_HOME=/usr/local/airflow
        env_file:
            - ${PATH_PREFIX}/poseidon/${ENV_FILE}
        ports:
            - "8080:8080"
        links:
            - postgres:postgres
            - fmeengine:fmeengine
        entrypoint: /usr/local/airflow/poseidon/custom_entrypoint.sh
        command: webserver

    scheduler:
        image: mrmaksimize/airflow:latest
        restart: always
        volumes:
            - ${PATH_PREFIX}/poseidon:/usr/local/airflow/poseidon
            - ${PATH_PREFIX}/poseidon/data:/data
            - ${PATH_PREFIX}/poseidon/logs:/usr/local/airflow/logs
        depends_on:
            - webserver
        environment:
            - LOAD_EX=n
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - EXECUTOR=Local
            - AIRFLOW_HOME=/usr/local/airflow
        env_file:
            - ${PATH_PREFIX}/poseidon/${ENV_FILE}
        links:
            - fmeengine:fmeengine
        entrypoint: /usr/local/airflow/poseidon/custom_entrypoint.sh
        command: scheduler -n 1

    fmeengine:
        image: safesoftware/fme-engine-2017:latest
        restart: always
        volumes:
            - ${PATH_PREFIX}/poseidon:/poseidon
            - ${PATH_PREFIX}/poseidon/data:/data
            - ${PATH_PREFIX}/poseidon/logs:/fmeengine/logs
        ports:
            - "7777:7777"
